# Generated by Django 5.1.1 on 2026-03-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date de verification de l email', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date de verification du numero de telephone', null=True),
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('purpose', models.CharField(choices=[('signup', 'Inscription')], default='signup', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'channel', 'purpose'], name='accounts_ve_user_id_e7bec2_idx'), models.Index(fields=['expires_at'], name='accounts_ve_expires_fb4ecf_idx')],
            },
        ),
    ]
