# Generated by Django 5.2.12 on 2026-04-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_change_required',
            field=models.BooleanField(default=False, help_text='Changer le mot de passe obligatoire à la prochaine connexion'),
        ),
    ]
