services:
  - type: web
    name: yalaz-web
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn aylaz.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: cron
    name: yalaz-recurring-transactions
    runtime: python
    schedule: "0 6 * * *"   # chaque jour à 06h00 UTC
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py generate_recurring_transactions
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
