"""Constants for listings app."""

MOROCCAN_CITIES = [
    'Agadir',
    'Al Hoceïma',
    'Asilah',
    'Azilal',
    'Azemmour',
    'Beni Mellal',
    'Berkane',
    'Berrechid',
    'Boujdour',
    'Bouznika',
    'Casablanca',
    'Chefchaouen',
    'Chichaoua',
    'Dakhla',
    'Dar Bouazza',
    'Debdou',
    'Demnate',
    'El Araïsh',
    'El Jadida',
    'El Kelaa des Sraghna',
    'Errachidia',
    'Essaouira',
    'Fez',
    'Figuig',
    'Guelmim',
    'Guercif',
    'Ifni',
    'Ifrane',
    'Inezgane',
    'Jerada',
    'Kénitra',
    'Khémisset',
    'Khénifra',
    'Khouribga',
    'Laayoune',
    'Larache',
    'Marrakech',
    'Meknès',
    'Midelt',
    'Moulay Idriss',
    'Nador',
    'Ouarzazate',
    'Ouazzane',
    'Oued Zem',
    'Oujda',
    'Rabat',
    'Salé',
    'Safi',
    'Saidia',
    'Sefrou',
    'Settat',
    'Sidi Ifni',
    'Sidi Kacem',
    'Skhirat',
    'Tafraout',
    'Tamanrasset',
    'Taounate',
    'Taourirt',
    'Tarfaya',
    'Taroudant',
    'Tata',
    'Taza',
    'Tétouan',
    'Tiflet',
    'Tinerhir',
    'Tiznit',
    'Volubilis',
    'Youssoufia',
    'Zagora',
]

MOROCCAN_CITIES_CHOICES = [(city, city) for city in sorted(set(MOROCCAN_CITIES))]

# Districts grouped by city - Real neighborhoods
MOROCCAN_DISTRICTS = {
    'Agadir': ['Drarga', 'Inezgane', 'Ait Melloul', 'Tikiouine', 'Talborjt', 'Secteur 29', 'Hay Masira', 'Tamazarte', 'Akreman'],
    'Al Hoceïma': ['Al Hoceïma Ville', 'Ajdir', 'Imzouren', 'Torres'],
    'Asilah': ['Asilah Ville', 'Asilah Medina', 'Asilah Kasbah'],
    'Azilal': ['Azilal Ville', 'Imirzguen', 'Tizi n\'Irhil', 'Ait Abdallah'],
    'Azemmour': ['Azemmour Médina', 'Azemmour Jedida'],
    'Beni Mellal': ['Beni Mellal Ville', 'Dar Ould Zaid', 'Zitoune', 'Tadla'],
    'Berkane': ['Berkane Ville', 'Berkane Médina', 'Sidi Slimane'],
    'Berrechid': ['Berrechid Ville', 'Sidi Slimane', 'Aït Slimane', 'Ben Ahmed'],
    'Boujdour': ['Boujdour', 'Boujdour Saha'],
    'Bouznika': ['Bouznika', 'Skhirat-Temara', 'Oulfa'],
    'Casablanca': ['Aïn Chock', 'Anfa', 'Ben M\'Sick', 'Bourgogne', 'Derb Sultan', 'Fez', 'Gueliz', 'Hay Chabab', 'Hay Dakhla', 'Hay Eldiraa', 'Hay Elkebda', 'Hay Essaada', 'Hay Faraji', 'Hay Hassani', 'Hay Ibrahimi', 'Hay Khalifa', 'Hay Mohammadi', 'Hay Mrabitin', 'Hay Moulay Rachid', 'Hay Nahda', 'Hay Rahma', 'Hay Salam', 'Hay Sidi Moumen', 'Hay Snahla', 'Hay Taqaddoum', 'Hay Yaaraqoub', 'Maarif', 'Medina', 'Mellah', 'Moulay Rachid', 'Oasis', 'Roches Noires', 'Sabat', 'Sbata', 'Sidi Bernoussi', 'Sidi Othmane', 'Skhirat-Temara', 'Souissi', 'Talbourja', 'Oulfa', 'Zenata', 'Zone Bab Doukkala', 'Zone Industrielle'],
    'Chefchaouen': ['Chefchaouen Médina', 'Chefchaouen Ville Nouvelle', 'Bab Onsar'],
    'Chichaoua': ['Chichaoua Centre', 'Oulad Brahim', 'Tamassint'],
    'Dakhla': ['Dakhla Ville', 'Dakhla Lagon'],
    'Dar Bouazza': ['Dar Bouazza', 'Mesouriya'],
    'Debdou': ['Debdou Ville', 'Debdou Médina', 'Angad'],
    'Demnate': ['Demnate Centre', 'Imi n\'Ifri'],
    'El Araïsh': ['Larache Médina', 'Larache Ville', 'Lixus'],
    'El Jadida': ['El Jadida Médina', 'El Jadida Côtiére', 'Oualidia', 'Sidi Abed'],
    'El Kelaa des Sraghna': ['El Kelaa Centre', 'Kasbah Tadla'],
    'Errachidia': ['Errachidia Centre', 'Erfoud'],
    'Essaouira': ['Essaouira Médina', 'Essaouira Ville', 'Sidi Kaouki', 'Guethary', 'Cap Sim'],
    'Fez': ['Fez Médina', 'Fez Nouvelle', 'Aïn Nokbi', 'Dihya', 'Hay Mjara', 'Hay Lmlih', 'Ziat', 'Agdal', 'Zouagha', 'Sefrou Road', 'Ifrane Road', 'Meknes Road', 'Mellah', 'Bab Sefra', 'Bab Ftoh', 'Bab Guissa', 'Dar Dbibagh', 'Doukkala', 'Talaa Kebira'],
    'Figuig': ['Figuig Ksar', 'Tazouta'],
    'Guelmim': ['Guelmim Centre', 'Asrir', 'Tamanart'],
    'Guercif': ['Guercif Ville', 'Taourirt'],
    'Ifni': ['Ifni Ville', 'Mirleft'],
    'Ifrane': ['Ifrane Centre', 'Michlifen'],
    'Inezgane': ['Inezgane Centre', 'Aglou', 'Tassila'],
    'Jerada': ['Jerada Centre', 'Jerada Mines'],
    'Kénitra': ['Kénitra Centre', 'Mediouna', 'Sals', 'Sidi Abdelaziz'],
    'Khémisset': ['Khémisset Centre', 'Sidi Mohammed Ben Abdellah'],
    'Khénifra': ['Khénifra Centre', 'Midelt Road'],
    'Khouribga': ['Khouribga Centre', 'Benzou', 'Had Kourt'],
    'Laayoune': ['Laayoune Centre', 'Laayoune Nord', 'Laayoune Sud', 'Laayoune Cité Loisance'],
    'Larache': ['Larache Médina', 'Larache Ville', 'Lixus', 'Tangier Road'],
    'Marrakech': ['Médina', 'Gueliz', 'Hivernage', 'Kasbah', 'Palmeraie', 'Saada', 'Mellah', 'Hay Hassani', 'Hay Salam', 'Hay Mohammadi', 'Dar el Baida', 'Sidi Youssef Ben Ali', 'Targa', 'Douar Lakhdar', 'M\'Hamid', 'Sidi Mimoun'],
    'Meknès': ['Meknès Médina', 'Meknès Nouvelle', 'Agdal', 'Sidi Said', 'Hay Hassan', 'Hay Mjara', 'Douar el Baraka', 'Bab Mansour', 'Bab Khemis', 'Mellah', 'Almohade'],
    'Midelt': ['Midelt Centre', 'Taza Road'],
    'Moulay Idriss': ['Moulay Idriss Centre', 'Zerhoune'],
    'Nador': ['Nador Centre', 'Nador Plage', 'Nador Médina', 'Beni Ensar'],
    'Ouarzazate': ['Ouarzazate Centre', 'El Kelaa', 'Kasbah'],
    'Ouazzane': ['Ouazzane Centre', 'Sidi Kacem'],
    'Oued Zem': ['Oued Zem Centre', 'Morocco'],
    'Oujda': ['Oujda Médina', 'Oujda Nouvelle', 'Angad', 'Hay Hassani', 'Hay Salam', 'Sidi Aïssa', 'Beni Drar'],
    'Rabat': ['Médina', 'Agdal', 'Yacoub El Mansour', 'Hay Riad', 'Takaddoum', 'Souissi', 'Hassan', 'Ocean', 'Hay Nahda', 'Hay Assifa', 'Salammbo', 'Grace Holland', 'Douar el Baraka', 'Bab Alou', 'Avenue de l\'Armée Royal', 'Akkari', 'Hay Ldraa'],
    'Salé': ['Salé Médina', 'Salé Tabriquet', 'Salé Nakhil', 'Hay Hassani', 'Hay Salam', 'Riad de Fez', 'Skhirat', 'Hay Es-Skhounah'],
    'Safi': ['Safi Médina', 'Safi Côtière', 'Cap Sim', 'Jorf Lasfar'],
    'Saidia': ['Saidia Plage', 'Saidia Ville'],
    'Sefrou': ['Sefrou Médina', 'Sefrou Nouvelle', 'Bhalil'],
    'Settat': ['Settat Centre', 'Hay Salam', 'Hay Hassani'],
    'Sidi Ifni': ['Sidi Ifni Ville', 'Mirleft'],
    'Sidi Kacem': ['Sidi Kacem Centre', 'Ksar el Kébir'],
    'Skhirat': ['Skhirat Centre', 'Temara'],
    'Tafraout': ['Tafraout Centre', 'Ameln'],
    'Tamanrasset': ['Tamanrasset Centre', 'In Gall'],
    'Taounate': ['Taounate Centre', 'Taza Road'],
    'Taourirt': ['Taourirt Centre', 'Jerada Road'],
    'Tarfaya': ['Tarfaya Centre', 'Tan Tan'],
    'Taroudant': ['Taroudant Médina', 'Taroudant Agadir Road', 'Taroudant Marrakech Road', 'Oulad Berhil'],
    'Tata': ['Tata Centre', 'Tafraout Road'],
    'Taza': ['Taza Médina', 'Taza Nouvelle', 'Taza Cascades'],
    'Tétouan': ['Tétouan Médina', 'Tétouan Ville Nouvelle', 'Bab Okla', 'Dersa', 'Hay Hassani', 'Hay Salam', 'Charf', 'Masnada'],
    'Tiflet': ['Tiflet Centre', 'Meknes Road'],
    'Tinerhir': ['Tinerhir Centre', 'Todra', 'Dades'],
    'Tiznit': ['Tiznit Médina', 'Tiznit Côtière', 'Aglou', 'Sidi Ifni Road'],
    'Volubilis': ['Volubilis Archéologie'],
    'Youssoufia': ['Youssoufia Centre', 'Sidi Bernoussi'],
    'Zagora': ['Zagora Centre', 'Tamegroute'],
}
