# Generated by Django 5.2.13 on 2026-04-27 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('listing_type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location')], default='sale', max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('villa', 'Villa'), ('riad', 'Riad'), ('land', 'Terrain'), ('office', 'Bureau / Local commercial'), ('other', 'Autre')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('surface', models.PositiveIntegerField(blank=True, help_text='Surface en m²', null=True)),
                ('rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Prix souhaité en MAD', max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_terrace', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours'), ('accepted', 'Accepté'), ('rejected', 'Refusé')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande vendeur',
                'verbose_name_plural': 'Demandes vendeurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seller_requests/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='core_financ_transac_f81567_idx',
            old_name='core_financi_transac_idx',
        ),
        migrations.RenameIndex(
            model_name='financialtransaction',
            new_name='core_financ_type_272d5a_idx',
            old_name='core_financi_type_st_idx',
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Membre du staff concerné par cette transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='payment_source',
            field=models.CharField(blank=True, choices=[('owner', 'Propriétaire'), ('client', 'Client'), ('both', 'Les deux')], help_text='Qui a payé la commission', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellerrequestimage',
            name='seller_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.sellerrequest'),
        ),
    ]
