# Generated by Django 5.2.13 on 2026-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sellerrequest_sellerrequestimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('surface', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estimation',
                'verbose_name_plural': 'Estimations',
                'ordering': ['-created_at'],
            },
        ),
    ]
