# Generated by Django 5.2.13 on 2026-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estimate_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Transaction récurrente'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('monthly', 'Par mois'), ('quarterly', 'Par trimestre'), ('yearly', 'Par an')], help_text='Fréquence de récurrence', max_length=20, null=True),
        ),
    ]
