# Generated by Django 5.2.13 on 2026-06-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_financialtransaction_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, help_text='Transaction source dont celle-ci a été générée automatiquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='core.financialtransaction'),
        ),
    ]
