# Generated by Django 5.1.1 on 2026-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_featured_report_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email pour être contacté (laissez vide pour cacher)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Téléphone pour être contacté', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=20, null=True),
        ),
    ]
