# Generated by Django 5.1.1 on 2026-03-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_owner_email_listing_owner_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Affichee en avant'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email pour etre contacte (laissez vide pour cacher)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Telephone pour etre contacte', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner_whatsapp',
            field=models.CharField(blank=True, help_text='Numero WhatsApp', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('published', 'Publiee'), ('rejected', 'Refusee')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='surface_area',
            field=models.PositiveIntegerField(help_text='Surface en m2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Contenu inapproprie'), ('fraud', 'Fraude/Arnaque'), ('fake', 'Annonce fake'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examine'), ('resolved', 'Resolu'), ('dismissed', 'Rejete')], default='pending', max_length=20),
        ),
    ]
