# Generated by Django 5.1.1 on 2026-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_is_featured_alter_listing_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='air_conditioning',
            field=models.BooleanField(default=False, help_text='Climatisation'),
        ),
        migrations.AddField(
            model_name='listing',
            name='balcony',
            field=models.BooleanField(default=False, help_text='Balcon'),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False, help_text='Meuble'),
        ),
        migrations.AddField(
            model_name='listing',
            name='garage',
            field=models.BooleanField(default=False, help_text='Garage'),
        ),
        migrations.AddField(
            model_name='listing',
            name='garden',
            field=models.BooleanField(default=False, help_text='Jardin'),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchen_equipped',
            field=models.BooleanField(default=False, help_text='Cuisine equipee'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False, help_text='Parking'),
        ),
        migrations.AddField(
            model_name='listing',
            name='security',
            field=models.BooleanField(default=False, help_text='Gardiennage/Securite'),
        ),
        migrations.AddField(
            model_name='listing',
            name='swimming_pool',
            field=models.BooleanField(default=False, help_text='Piscine'),
        ),
        migrations.AddField(
            model_name='listing',
            name='terrace',
            field=models.BooleanField(default=False, help_text='Terrasse'),
        ),
    ]
