# Generated by Django 5.2.13 on 2026-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_publicinquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('villa', 'Villa'), ('land', 'Terrain'), ('office', 'Bureau'), ('commercial', 'Local commercial')], max_length=20),
        ),
    ]
