# Generated by Django 5.2.13 on 2026-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='reference',
            field=models.CharField(blank=True, db_index=True, help_text='Référence unique (ex : CAS-APT-V-0042)', max_length=20, unique=True),
        ),
    ]
